### ISSUE TITLE
Attachments take quite a while to load from S3 bucket 

### ISSUE THREAD

**Issue by bheemvennapureddy** [testomatio/app#930] opened 2024-02-07 05:22 UTC
Attachments take quite a while to load from S3 bucket 

https://share.zight.com/rRuBkZQo

**Comment by poliarush** [comment] 2024-02-07 09:49
@littlefrontender is it frontend??

**Comment by poliarush** [comment] 2024-02-07 09:51
@bheemvennapureddy I think we need to see your Network from Console Dev Tools, could you please send us .har file for recoded session, 

also, is it reproducible all the times? what is the speed of your internet connection?

**Comment by littlefrontender** [comment] 2024-02-07 10:04
@poliarush i think not. Backend send artifacts with delay, but s3 may works slow sometimes

**Comment by poliarush** [comment] 2024-02-07 10:09
@bheemvennapureddy we need more details from chrome dev console

**Comment by TetianaKhomenko** [comment] 2024-06-21 14:56
Hi @bheemvennapureddy! We are closing the ticket for now as there are not enough details from your side. Please re-open it and add the requested info if the issue is still present for you. Thanks!

**Closed by TetianaKhomenko** 2024-06-21 14:56 UTC
Labels: bug, priority low, artifacts
