### ISSUE TITLE
Tests artifacts are not accesible from "Runs" screen using private AWS Bucket

### ISSUE THREAD

**Issue by AngelM-GL** [testomatio/app#565] opened 2021-11-30 14:59 UTC
**Describe the bug**
We've configured and connected our private AWS bucket to our Testomat project using "Settings > Artifacts" screen. We have set as well the required S3 parameters in our `.env` file as it is described in the documentation (https://docs.testomat.io/usage/test-artifacts/#private-access) , but when it comes to view the artifacts on "Runs" screen, it fails, as it tries to query it as if it still were on public bucket access, instead of private.

**To Reproduce**
1. Go to "Settings > Artifacts"
2. Configure a private AWS bucket
3. Run an execution for CodeceptJS Tests
4. Run ends with message ""
4. See the run report created in "Runs" screen
5. The attachment of the test artifact has succeded, but it is not possible to access to it.

**Expected behavior**
1. Go to "Settings > Artifacts"
2. Configure a private AWS bucket
3. Run an execution for CodeceptJS Tests
4. Run ends with message ""
4. See the run report created in "Runs" screen
5. You can see the artifact attached

**Screenshots**
![Captura de pantalla 2021-11-30 a las 14 43 37](https://user-images.githubusercontent.com/80691572/144059807-98636a49-1906-40da-98f0-5213024fa13f.png)

![Captura de pantalla 2021-11-30 a las 14 47 15](https://user-images.githubusercontent.com/80691572/144059843-ca80f7b0-0dae-4632-b42a-a98dfbfc0e14.png)

![Captura de pantalla 2021-11-30 a las 14 43 49](https://user-images.githubusercontent.com/80691572/144059872-18121ac1-7c3c-4726-aba5-6c093920d93c.png)

![Captura de pantalla 2021-11-30 a las 15 59 17](https://user-images.githubusercontent.com/80691572/144071281-4a11bff7-7393-44ef-b99c-855e356f6d69.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey (12.0.1)
 - Browser: Chrome 
 - Browser Version: 96.0.4664.55

**Additional context**
Using     

```
"@testomatio/reporter": "^0.4.4",
"codeceptjs": "^3.2.2",
"playwright": "^1.16.3"

```

**Comment by DavertMik** [comment] 2021-11-30 23:35
Thanks, @AngelM-GL looks like the error you encountered was caused by special chars like `@` in URL
We made a hotfix and it should be working for you in about 20 mins

**Comment by AngelM-GL** [comment] 2021-12-01 10:48
Yes, we can see the artifacts now, thank you very much for your support :) You can close this ticket

**Comment by TetianaKhomenko** [comment] 2021-12-01 10:59
@AngelM-GL thank you for the feedback!
closing this issue as fixed.

**Closed by TetianaKhomenko** 2021-12-01 10:59 UTC
Labels: bug, priority high, reporting
