### ISSUE TITLE
A test case position is changed to the previous state after opening another test case or closing and re-opening the test suit

### ISSUE THREAD

**Issue by Tny6918** [testomatio/app#936] opened 2024-02-13 10:24 UTC
*A test case position is changed to the previous state after opening another test case or closing and re-opening the test suit**

**To Reproduce**
1. Go to 'Dashboard'
2. Click on the created before test suit with test cases and create a new test case A
3. change its position
4. open another test case or close and re-open the test suit

**Expected behavior**
test case A position is saved

**Screenshots**

https://github.com/testomatio/app/assets/43401901/8b852244-a0ee-4586-b390-4199837da814

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Browser Version [121.0.6167.161]
 - Application: [production]

**Comment by littlefrontender** [comment] 2024-02-13 12:42
issue doesn't reproduce. I think it is already fixed

**Comment by TetianaKhomenko** [comment] 2024-02-13 13:02
@Tny6918 the issue was fixed. The fix will be published in the upcoming release.

**Comment by TetianaKhomenko** [comment] 2024-02-15 18:31
@Tny6918 the fix is live now

**Comment by Tny6918** [comment] 2024-03-14 11:28
@TetianaKhomenko the issue is again actual on prod

**Comment by littlefrontender** [comment] 2024-03-15 09:07
@TetianaKhomenko I couldn't reproduce this on beta. I think it is already fixed.

**Comment by TetianaKhomenko** [comment] 2024-03-25 19:13
@littlefrontender still present for BDD projects

**Comment by TetianaKhomenko** [comment] 2024-03-25 20:10
Hi @Tny6918! The issue should be fixed in the upcoming release.

**Closed by TetianaKhomenko** 2024-03-25 20:10 UTC
Labels: bug, bdd, priority medium, test tree
