### ISSUE TITLE
Uploaded files don't appear in test case attachments

### ISSUE THREAD

**Issue by Olia-Kastsiukovich** [testomatio/app#124] opened 2020-06-03 19:40 UTC
Enviroment: Win 10, Chrome v.83.0.4103.61

Expected result: Uploaded files sould be available to view
Actual result: Uploaded file (image png, 8.3 kB)  doesn't available to view

![image](https://user-images.githubusercontent.com/66385534/83681499-2f702e00-a5eb-11ea-89b2-814f523e65fb.png)

**Comment by poliarush** [comment] 2020-06-03 19:50
please attach file that was used for upload.
is it constantly reproducible?

**Comment by koushikmohan1996** [comment] 2020-06-05 08:40
@Olia-Kastsiukovich Is it happening only in demo projects?

**Comment by poliarush** [comment] 2020-06-05 14:09
@koushikmohan1996 no, it's also reproduced on standard projects

**Comment by koushikmohan1996** [comment] 2020-06-08 05:51
@poliarush I tried with both drag drop and upload button. Both works for me. Can you add me to the project with issue. I am not sure what's causing this issue

**Comment by poliarush** [comment] 2020-06-08 19:18
now it's working fine for me
@Olia-Kastsiukovich  please check it on your side

**Comment by Olia-Kastsiukovich** [comment] 2020-06-08 19:28
Yes, I cheked thorougly and on beta its work fine - all file attaches and i can delete them or download.

**Comment by poliarush** [comment] 2020-06-08 19:29
Ok, then we can close it.

**Closed by poliarush** 2020-06-08 19:29 UTC
Labels: bug, editor
