### ISSUE TITLE
[BE] Deleting the "Run Group" with blank name cause 500 error

### ISSUE THREAD

**Issue by AnisimovDenys03** [testomatio/app#793] opened 2023-08-18 11:34 UTC
**Steps to Reproduce:**

1. Open  https://app.testomat.io/

2. Sign in

3. Go to the **“Runs”** page

4. Click on **“New Group”** button

5. In **“Name of Group”** field past the space

6. Fill all required fields

7. Click on the **“Save”** button

8. Click on the **“Delete”** button

**Actual Result**: Deleting operation cause 500 error

**Expected Result:** Group was successfully deleted
![image-20230814-151608](https://github.com/testomatio/app/assets/140817860/bffac3b5-d54c-4b7a-b504-dc3637c9bdca)
![image-20230814-151632](https://github.com/testomatio/app/assets/140817860/4d69b3cc-d966-4baa-b214-187fac716610)

**Comment by Fro0z1k** [comment] 2023-08-28 10:58
@TetianaKhomenko Greetings! I can't reproduce this behavior. 
<img width="239" alt="Screenshot 2023-08-28 at 13 52 34" src="https://github.com/testomatio/app/assets/7832212/581721d6-b110-41c3-a3c9-f8e3aa74c283">
<img width="440" alt="Screenshot 2023-08-28 at 13 52 51" src="https://github.com/testomatio/app/assets/7832212/ed477aba-abd0-41d3-91e9-b335b147fdf6">

https://github.com/testomatio/app/assets/7832212/45a86811-9af8-416e-9662-b3a5f114dedc

**Comment by TetianaKhomenko** [comment] 2023-08-28 22:18
It seems that the previous fix resolved this problem. closing as done

**Closed by TetianaKhomenko** 2023-08-28 22:18 UTC
Labels: bug, priority medium
