### ISSUE TITLE
Can't multiselect different set of tests-suites

### ISSUE THREAD

**Issue by RohalskyiOleksii** [testomatio/app#879] opened 2023-11-22 15:23 UTC
**Describe the bug**
multiselection resets if trying to combine full suite select with few tests from other one

**To Reproduce**
1. Go to repository
2. Click on multiselection
3. Try to multiselect full 1suite + couple of tests from another 2suite

**Expected behavior**
Multiselection works

**Screenshots**
![image](https://github.com/testomatio/app/assets/132286699/87d0637e-5f13-4acb-966c-afa41d366361)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome

**Comment by TetianaKhomenko** [comment] 2023-11-22 15:28
Hi! This is not a bug. There is no way to apply the same action to suites and tests simultaneously. So suites and tests should be picked separately.

**Comment by RohalskyiOleksii** [comment] 2023-11-22 15:33
> Hi @RohalskyiOleksii ! This is not a bug. There is no way to apply the same action to suites and tests simultaneously. So suites and tests should be picked separately.

what if tester should select 2 full suites _and 3-4 tests from other suite that contains >100tests_? 
any good UX solution to this?

**Comment by TetianaKhomenko** [comment] 2024-03-22 19:56
Hi @RohalskyiOleksii! The issue was fixed by adding `Select all tests` option on the suite level. This improvement is live now so you can try it. Please see the short demo below.

https://github.com/testomatio/app/assets/77803888/a5a2a6bb-34bc-47a4-a040-635478dd70c7

**Closed by TetianaKhomenko** 2024-03-22 19:56 UTC
Labels: bug, priority medium, test tree, multiselect
