### ISSUE TITLE
Bitbucket Integration for Testomatio Pipe

### ISSUE THREAD

**Issue by itz4blitz** [testomatio/app#991] opened 2024-04-29 17:24 UTC
**Is your feature request related to a problem? Please describe.**
Our team uses Bitbucket for our pipeline and would like the ability to include the testomatio test summary into our PR's

**Describe the solution you'd like**
When we run our tests in CI and they have completed, the summary is included in the PR in Bitbucket.

**Describe alternatives you've considered**
None at this time

**Additional context**
None at this time

**Comment by poliarush** [comment] 2024-04-30 22:21
it's about testomat.io pipe like for github

<img width="822" alt="2024-05-01_00 20 30@2x" src="https://github.com/testomatio/app/assets/325722/29bc6985-a0ce-4bd4-8c87-5513913ad0b4">

**Comment by poliarush** [comment] 2024-04-30 22:22
@DavertMik can we implement it for BitBucket?

**Comment by poliarush** [comment] 2024-07-16 13:24
related to https://github.com/testomatio/app/issues/991

**Comment by AZANIR** [comment] 2024-08-15 10:36
@itz4blitz  We have prepared the bitbucket pipe for release, try to use the beta version in your project, there may be comments or suggestions.

Here is the docs https://docs.testomat.io/reference/reporter/pipes/bitbucket/

```
"@testomatio/reporter": "^1.4.13-beta-bitbucket-pipe"
```

![report](https://github.com/testomatio/reporter/raw/master/docs/pipes/images/bitbucket.png)

**Comment by poliarush** [comment] 2024-08-15 19:22
@itz4blitz please try it and let us know your feedback

**Comment by AZANIR** [comment] 2024-10-01 17:59
The issue is closed as the integration with Bitbucket has been successfully completed. After the CI pipeline finishes, the Testomat.io test report is now correctly added to the Pull Request in Bitbucket, as requested. The screenshot above shows the test report with all tests passing (4 tests run, 0 failed, 0 skipped), along with detailed timing for each test.

If there are any further questions or improvements needed, we can revisit this issue. Thank you for the request!

**Closed by AZANIR** 2024-10-01 17:59 UTC
Labels: enhancement, ci\cd, priority medium, bitbucket
