### ISSUE TITLE
Import command adds a blank space in front of the test ids each time it runs

### ISSUE THREAD

**Issue by XavierDeMontis** [testomatio/app#578] opened 2022-04-28 11:54 UTC
**Describe the bug**
Each and every time you run the import command you notice one more blank space is added in front of your test ids. 

**To Reproduce**
1. Run the testomat import command (example : npx check-cucumber@latest --codeceptjs '**/*.feature' --dir test/e2e/features --update-ids --create --keep-structure ) with feature files already having test ids ideally
2. Now look how your feature files changed (here as an example you can see a printscreen where I ran the import command three times in a row)
![image](https://user-images.githubusercontent.com/67690774/165746254-59371c19-cb31-465a-982c-c6b728fdcff4.png)

**Expected behavior**
I don't want any blank to be added where it's unnecessary. It generates noise and make it more difficult to review.

**Screenshots**
![image](https://user-images.githubusercontent.com/67690774/165746254-59371c19-cb31-465a-982c-c6b728fdcff4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome
 - Browser Version [e.g. 22]
 - Application: [production or beta] 

**Additional context**

**Comment by TetianaKhomenko** [comment] 2022-05-01 12:57
Hi @XavierDeMontis! The issue is fixed with check-cucumber 0.5.7 version.

**Closed by TetianaKhomenko** 2022-05-01 12:57 UTC
Labels: bug, bdd, import\export, codeceptjs, priority medium
