### ISSUE TITLE
Fix CSS styling of App

### ISSUE THREAD

**Issue by martin-pikalek** [testomatio/app#606] opened 2022-08-16 02:23 UTC
**Describe the bug**
Several pages within App have wrong styling so user cannot see them clearly

**To Reproduce**
1. Go to 'https://app.testomat.io/projects/$projectId/'
2. Observe pages from screenshots
3. Compare screenshots with App

**Expected behavior**
Pages should be properly styled so whole page content should be visible and accessible

**Screenshots**
<img width="1438" alt="Screenshot 2022-08-16 at 4 06 40" src="https://user-images.githubusercontent.com/57229273/184783706-97402a45-a688-4779-bfb8-0d3eeab09f94.png">
<img width="1438" alt="Screenshot 2022-08-16 at 4 16 24" src="https://user-images.githubusercontent.com/57229273/184784197-bd74d0f6-d99f-4af0-b946-038f03b16f4b.png">

**Desktop:**
 - OS: [MacOS Monterey 12.3.1]
 - Browser [chrome 104.0.5112.79, safari 15.4]
 - Application: [production]

**Comment by TetianaKhomenko** [comment] 2022-09-02 12:18
Hi @martin-pikalek! Could you please give more context to the issue? 
As I see the problem is that the Settings popup does not close automatically. Am I right?

**Comment by martin-pikalek** [comment] 2022-09-02 12:27
Hi @TetianaKhomenko  The biggest issue is that even when I have browser window across fullscreen, left main navigation menu (also sort mode button) is for example cropped (and scrolling is not enabled so I cannot even scroll to last item - profile item). I tried it in different browsers (and same issue). And yes, I would expect that if settings submenu is opened, that for example template edit form context would be resized to be able to see it whole (not let settings submenu overflow it - especially if the submenu do not have any styling borders etc.) . Also I found out that for example Import From CSV from is only in light mode (even when whole application is in dark mode) which hurting eyes :)

**Comment by TetianaKhomenko** [comment] 2022-09-09 12:27
Hi @martin-pikalek! Thank you for the details, we appreciate your help. Can we ask you to add some screenshots regarding this part?

> The biggest issue is that even when I have browser window across fullscreen, left main navigation menu (also sort mode button) is for example cropped (and scrolling is not enabled so I cannot even scroll to last item - profile item). I tried it in different browsers (and same issue).

**Comment by martin-pikalek** [comment] 2022-09-13 13:15
Hi @TetianaKhomenko,
I think my issues can be easily reproduced.  I am using MacBook (**screen 13,3-inch 2560 × 1600 retina**). 
But I am sending you screenshots for each issue 😃  :

### 1. Import From CSV (white form in dark mode)
<img width="1563" alt="Screenshot 2022-09-13 at 13 22 27" src="https://user-images.githubusercontent.com/57229273/189889736-9f3661f9-6a66-487c-8549-f5975fcaa0e3.png">

### 2. Sort mode button (in any window size - button is partially out of viewport)
<img width="1584" alt="Screenshot 2022-09-13 at 13 31 02" src="https://user-images.githubusercontent.com/57229273/189890678-7c1f2f56-b84d-4c0b-8ae6-e50b2fee1ba4.png">

### 3. Left main navigation (in window with lower height - items can be pushed outside of viewport but navigation is not scrollable)
- this happens on my MacBook built-in display always, even when browser window is on fullscreen
<img width="241" alt="Screenshot 2022-09-13 at 13 35 15" src="https://user-images.githubusercontent.com/57229273/189891240-8cc4dab8-948b-4a38-948e-466e78d844d7.png">

### 4. Right pop-ups (for edit forms etc.) are unpredictable by sizing
- because of random sizing some features are not visible for user at first glance (for example ESC button or add test input)
- but at least this content is scrollable so it is accessible if user know it is there

<img width="1802" alt="Screenshot 2022-09-13 at 15 00 18" src="https://user-images.githubusercontent.com/57229273/189909075-b9fa68ff-4cbe-4174-ac65-5dfcfb628346.png">
<img width="1802" alt="Screenshot 2022-09-13 at 15 00 24" src="https://user-images.githubusercontent.com/57229273/189909088-9f190762-70c9-4948-b8e1-3b912f06e334.png">
<img width="1802" alt="Screenshot 2022-09-13 at 15 00 29" src="https://user-images.githubusercontent.com/57229273/189909096-7e693ebd-cf5c-4e7c-890f-252ee1e18fb8.png">

### 5. Right pop-ups are not always on top (can be pushed behind left submenu)
- pop-ups should be always on top
<img width="1666" alt="Screenshot 2022-09-13 at 14 58 05" src="https://user-images.githubusercontent.com/57229273/189910104-83c201b2-573a-4a7c-a252-2624fa2155a4.png">
<img width="1556" alt="Screenshot 2022-09-13 at 15 13 07" src="https://user-images.githubusercontent.com/57229273/189910364-57f495f2-18b3-4f6a-a305-3d8471f76b95.png">

**Comment by TetianaKhomenko** [comment] 2022-09-14 04:17
Hi @martin-pikalek! Thanks a lot for these additional screenshots! Really useful!
The good news - some of these bugs will be fixed with the upcoming release 🥳

**Comment by TetianaKhomenko** [comment] 2022-09-27 07:07
created separate tickets for further improvements:
https://github.com/testomatio/app/issues/612
https://github.com/testomatio/app/issues/611

**Comment by TetianaKhomenko** [comment] 2022-09-27 07:07
closing this issue as fixed

**Closed by TetianaKhomenko** 2022-09-27 07:07 UTC
Labels: bug, ui\ux, priority low
