### ISSUE TITLE
S3 Private configuration can not be really disable 

### ISSUE THREAD

**Issue by komarov-v** [testomatio/app#566] opened 2021-12-03 17:02 UTC
**Describe the bug**
S3 private settings can't be switched off 

**To Reproduce**
1. Go to 'Artifacts'
2. Click on 'Use Private URLs for Test Artifacts' (to switch on)
3. Click on 'Use Private URLs for Test Artifacts' (to switch off)
4. Go to 'Tests'
5. Run any test on CI
6. Go to 'Runs' and open latest run
7. See error 'Invalid S3 config 'BUCKET' is not set

**Expected behavior**
The 'BUCKET' setting is not apply, when  'Use Private URLs for Test Artifacts' is turned off.

**Additional context**
S3 is configured as a public storage

**Comment by TetianaKhomenko** [comment] 2021-12-07 11:42
The issue significantly affects work with Run Report results. 
Please see the attachments on this issue

![screencast 2021-12-07 13-29-26](https://user-images.githubusercontent.com/77803888/145022954-1643c1a4-3f73-459a-a7d9-7cf74cedaf42.gif)

**Comment by TetianaKhomenko** [comment] 2021-12-09 11:06
The issue is still present for existing projects

![image](https://user-images.githubusercontent.com/77803888/145385069-544c7255-b195-4645-b4ce-2d5440a06781.png)

![image](https://user-images.githubusercontent.com/77803888/145385210-10eafbff-dddd-40f2-bf3f-64532a63d24b.png)

**Comment by DavertMik** [comment] 2021-12-09 19:55
Fixed

**Comment by TetianaKhomenko** [comment] 2021-12-13 09:40
closing this as fixed

**Closed by TetianaKhomenko** 2021-12-13 09:40 UTC
Labels: bug, reporting, priority blocker

**Comment by TetianaKhomenko** [comment] 2021-12-17 12:22
@komarov-v the fix is released on https://app.testomat.io/  😉
