### ISSUE TITLE
`npx check-tests … --update-ids` delete all new lines in tests

### ISSUE THREAD

**Issue by kirhike** [testomatio/app#556] opened 2021-10-27 07:16 UTC
**Describe the bug**
`npx check-tests … --update-ids` delete all new lines in tests

**Screenshots**
Before: 
<img width="807" alt="Screenshot 2021-10-26 at 17 44 01" src="https://user-images.githubusercontent.com/40691768/139018051-1378ddf2-933c-45ca-b21c-87301a59c91e.png">

After:
<img width="820" alt="Screenshot 2021-10-26 at 17 44 56" src="https://user-images.githubusercontent.com/40691768/139018098-abff477f-d4e5-4c23-a176-e5d7e28502b0.png">

**Comment by TetianaKhomenko** [comment] 2021-11-12 08:46
The issue is fixed with check-tests v0.7.0

**Closed by TetianaKhomenko** 2021-11-12 08:46 UTC
Labels: bug, priority high, import\export, codeceptjs
